### ISSUE TITLE
redis.clients.jedis.exceptions.JedisDataException: NOAUTH Authentication required.

### ISSUE THREAD

**Issue by songjiesdnu** [mybatis/redis-cache#19]
```
org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.exceptions.PersistenceException: 
### Error querying database.  Cause: redis.clients.jedis.exceptions.JedisDataException: NOAUTH Authentication required.
### Cause: redis.clients.jedis.exceptions.JedisDataException: NOAUTH Authentication required.
	at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:75)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:371)
	at org.mybatis.spring.SqlSessionTemplate.selectList(SqlSessionTemplate.java:198)
	at org.apache.ibatis.binding.MapperMethod.executeForMany(MapperMethod.java:119)
	at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:63)
	at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:52)
	at com.smarttrip.service.impl.StartDateService.selectByConditionMap(StartDateService.java:80)
	at com.smarttrip.service.impl.StartDateServiceTest.test(StartDateServiceTest.java:33)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:606)
```

has anybody account this problem?when i use redis-cli to connect redis, the password i write in redis.properties is white.
```
host=xxxx.xxxx.xxxx.xxxx
port=6379
connectionTimeout=5000
soTimeout=5000
password=111111
database=0
clientName=develop
```

**Comment by songjiesdnu** [comment]
the version i use is ```1.0.0-beta1```,that can achieve from maven repository.
when i use the current version ```1.0.0-beta2-SNAPSHOT```,the problem solved.

**Comment by emacarron** [comment]
Great. Note that the right version is 1.0.0-beta2
http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22org.mybatis.caches%22%20AND%20a%3A%22mybatis-redis%22
