### ISSUE TITLE
Could not get a resource from the pool

### ISSUE THREAD

**Issue by mlc0202** [mybatis/redis-cache#7]
When i use redis-cache in my project ,it throws exception,as you see,"Could not get a resource from the pool".
this is more infomation
   
  ### Cause: redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool] with root cause
java.net.ConnectException: Connection refused: connect
	at java.net.DualStackPlainSocketImpl.waitForConnect(DualStackPlainSocketImpl.java)
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:85)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:579)
	at redis.clients.jedis.Connection.connect(Connection.java:144)
	at redis.clients.jedis.BinaryClient.connect(BinaryClient.java:71)
	at redis.clients.jedis.BinaryJedis.connect(BinaryJedis.java:1783)
	at redis.clients.jedis.JedisFactory.makeObject(JedisFactory.java:65)
	at org.apache.commons.pool2.impl.GenericObjectPool.create(GenericObjectPool.java:819)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:429)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:360)
	at redis.clients.util.Pool.getResource(Pool.java:40)
	at redis.clients.jedis.JedisPool.getResource(JedisPool.java:84)

**Comment by mlc0202** [comment]
I used redis 3.0.3 with centos 6.2

**Comment by live106** [comment]
Have you config the redis.properties file?
Note that the default host is "localhost" and port 6379.

**Comment by songjiesdnu** [comment]
I had the same problem as you.Finally i debug the source code, and found that there is a bug.
File:RedisConfigurationBuilder.java(line:100)
the orginal code is: ````jedisConfig.setHost("localhost");``
i modified this code to: ```jedisConfig.setHost(config.getProperty("redis.ip"));```
and this solved the problem.

**Comment by emacarron** [comment]
Hi all. 

The line "jedisConfig.setHost("localhost");" was indeed wrong but made no difference. If the host is not set in the properties file then "localhost" is used (See RedisConfig).

So if you are getting a connection proproblem I would 1st check you host and port.
